// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr40XQFQOK7jYGTiv0b1HjGrPy0j3UNDs',
    appId: '1:855006989889:web:4458925882fd3ca68500c0',
    messagingSenderId: '855006989889',
    projectId: 'connectabc-97e5b',
    authDomain: 'connectabc-97e5b.firebaseapp.com',
    storageBucket: 'connectabc-97e5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3WOL5zjV33gMXgo-ww8kjGEcKfxqM1oc',
    appId: '1:855006989889:android:3f8b539c9a1626c88500c0',
    messagingSenderId: '855006989889',
    projectId: 'connectabc-97e5b',
    storageBucket: 'connectabc-97e5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDkL4zZRDoBjp7kzJSorYnWOPYwopOC4k',
    appId: '1:855006989889:ios:14b807cc8c4887908500c0',
    messagingSenderId: '855006989889',
    projectId: 'connectabc-97e5b',
    storageBucket: 'connectabc-97e5b.appspot.com',
    iosClientId: '855006989889-1kusc5itpio79fcebi13jjm7k343u61n.apps.googleusercontent.com',
    iosBundleId: 'com.example.mmoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDkL4zZRDoBjp7kzJSorYnWOPYwopOC4k',
    appId: '1:855006989889:ios:14b807cc8c4887908500c0',
    messagingSenderId: '855006989889',
    projectId: 'connectabc-97e5b',
    storageBucket: 'connectabc-97e5b.appspot.com',
    iosClientId: '855006989889-1kusc5itpio79fcebi13jjm7k343u61n.apps.googleusercontent.com',
    iosBundleId: 'com.example.mmoMobile',
  );
}
